// MDI name -> codepoint table (served by the integration, generated by tools/build-icons.mjs)
let table: Map<string, number> | null = null;
let loading: Promise<Map<string, number>> | null = null;

export function loadIcons(url: string): Promise<Map<string, number>> {
  if (table) return Promise.resolve(table);
  loading ??= fetch(url)
    .then((r) => r.json() as Promise<Record<string, string>>)
    .then((data) => {
      table = new Map(Object.entries(data).map(([k, v]) => [k, parseInt(v, 16)]));
      return table;
    });
  return loading;
}

export function setIconTable(map: Map<string, number>): void {
  table = map;
}

export function iconChar(icon: string | undefined | null): string | null {
  if (!icon || !icon.startsWith("mdi:") || !table) return null;
  const cp = table.get(icon.slice(4));
  return cp === undefined ? null : String.fromCodePoint(cp);
}

export function searchIcons(query: string, limit = 60): string[] {
  if (!table) return [];
  const q = query.toLowerCase().replace(/^mdi:/, "").trim();
  const starts: string[] = [];
  const contains: string[] = [];
  for (const name of table.keys()) {
    if (!q || name.startsWith(q)) starts.push(name);
    else if (name.includes(q)) contains.push(name);
    if (starts.length >= limit) break;
  }
  return [...starts, ...contains].slice(0, limit).map((n) => `mdi:${n}`);
}
